### PR TITLE
Copy request headers after assign content

### PR DESCRIPTION
**Pull request by DaniilSokolyuk**
Copy request headers before content assign is very bad idea
For example Content-Type is content header and Content is null when we try copy this header
Original https://github.com/aspnet/Proxy/blob/master/src/Microsoft.AspNetCore.Proxy/ProxyAdvancedExtensions.cs#L57

### CODE REVIEW

**Comment by twitchax** [comment]
Hi @DaniilSokolyuk, I'm not actually sure why this is a bad idea.  Before the request is made, it should not matter whether headers or content is applied first, correct?

Regardless, the tests are failing, so that will need to be addressed first.

```
gitpod /workspace/AspNetCore.Proxy $ dotnet test
Test run for /workspace/AspNetCore.Proxy/src/Test/bin/Debug/netcoreapp2.0/AspNetCore.Proxy.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 16.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:08.5028007]     AspNetCore.Proxy.Tests.UnitTests.ProxyAttributePostWithFormRequest [FAIL]
  X AspNetCore.Proxy.Tests.UnitTests.ProxyAttributePostWithFormRequest [750ms]
  Error Message:
   Assert.Equal() Failure
Expected: (null)
Actual:   JValue []
  Stack Trace:
     at AspNetCore.Proxy.Tests.UnitTests.ProxyAttributePostWithFormRequest() in /workspace/AspNetCore.Proxy/src/Test/UnitTests.cs:line 70
--- End of stack trace from previous location where exception was thrown ---

Test Run Failed.
Total tests: 12
     Passed: 11
     Failed: 1
 Total time: 12.0172 Seconds
```

**Comment by twitchax** [comment]
For what it's worth, I am guessing that the current behavior is actually the desired behavior.  Basically, we want to match the headers as closely as possible, but we want to allow the true content of the request to overwrite those applied headers, if needed.

**Comment by DaniilSokolyuk** [comment]
@twitchax thats bad idea because we loose all content headers, content is null when we try to assign headers.
[This line](https://github.com/twitchax/AspNetCore.Proxy/blob/5d5e56dfd0be2cc6c3e3a857592309e02efec73e/src/Core/Helpers.cs#L66 ) does not make sense because this code is not reachable.
Test **ProxyAttributePostRequest** is wrong, because jsonplaceholder.typicode.com is not sensitive to content headers (Content-Type, Content-Length)
Test is fixed, test fail because FormUrlEncodedContent not needed, as I understand it was a fix for missing content headers
I am added a new test using postman-echo.com, for content header validate

**Comment by twitchax** [comment]
OK, I see what you are saying.

Will this re-introduce the issue that originally created the header changes?  Just that the scenario was invalid due to poor headers?

Also, can you please remove the extraneous braces?  This project generally uses a braces-less style.

**Comment by twitchax** [comment]
@DaniilSokolyuk, ping. :)

**Comment by DaniilSokolyuk** [comment]
Braces fixed.
I do not really understand what kind of problem you are talking about)
I had a problem that my code is sensitive to Content type headers, and nothing worked for me)
If you about FormUrlEncodedContent, it is no longer needed because content headers is correctly assign

**Comment by twitchax** [comment]
Yeah, thanks for the clarification.

**Pull request merged**
