### PR TITLE
add callback for process response before return.

### PR DESCRIPTION
**Pull request by urffin**
#15

### CODE REVIEW

**Comment by twitchax** [comment]
@urffin, thanks!  Give me a few days to check this out.  Busy week!

**Comment by twitchax** [comment]
@urffin, I'm not sure if `Stream` to `Stream` is the right way to do this, but I have no other recommendations.  Can you remove all of the style changes, though?  Makes it hard for me to discern your changes from the style changes.

**Comment by urffin** [comment]
@twitchax, i'm try revert inserted spaces and place for block start (if i right understand what you mean by style changes) can you check it?

**Comment by urffin** [comment]
@twitchax still busy? :)

**Comment by twitchax** [comment]
@urffin, sorry, whole family has been sick.  Still mulling over the `Stream` question.  Wondering if we should look into `Pipe`.

**Comment by urffin** [comment]
Not worry :) Can you a bit explain what `Pipe` you mean, than i can a bit investigate it?

**Comment by twitchax** [comment]
@urffin, I think I have come up with a better solution that I am working on.

**Comment by urffin** [comment]
> @urffin, I think I have come up with a better solution that I am working on.

Can you tell what solution? :)

**Comment by twitchax** [comment]
Closing in favor of #23.

**Pull request closed without merging**
