### PR TITLE
AspNetCore.Proxy 4.0.0 Release

### PR DESCRIPTION
**Pull request by twitchax**

### CODE REVIEW

**Comment by twitchax** [comment]
@christianrr, @PaulUpson, @dbettin, @kylepope-ge, @havarnov, @waxingsatirical.

Any of you care to take a look?  I moved from `CLRF` to `LF`, so you may want to ignore whitespace.

Also, the architecture changed quite a lot, so checkout the changes to the README first, I think.  Honestly, the architecture is so different, you may not even want to look at the diff.  However, the design goal was to make it _feel_ more like ASP.NET Core 3. :)

**Comment by kylepope-ge** [comment]
Thanks @twitchax -- I appreciate the work you did here. This is excellent.

I took a look at the code changes, and don't have any specific recommendations for change/improvements. Honestly, I like the refactor you did here and the docs make it clear on how to use it. My only (extremely minor) nitpick is I didn't realize that the main extension methods were moved to the Extensions namespace, which I didn't realize until I looked at the code (i.e. extension methods aren't very discoverable). But that's pretty minor and probably not even worth changing or calling out since it's pretty obvious once you look.

Anyway, I pulled down the latest changes and tried it out in my own code -- everything is pretty straightforward and works as I would expect. Unless others have specific feedback here, I'd say we are good to go. 

Thanks again for creating and maintaining such a useful library!

**Comment by twitchax** [comment]
@kylepope-ge, that makes sense.  Do you think it would make them more discoverable if I move the extensions up to the top level?

**Comment by twitchax** [comment]
kylepope-ge, @PaulUpson, I moved them up a level! :)

**Pull request merged**
